version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: timokoesters:master    # Required. Must be in the same fork network.
    mergeMethod: rebase
label: ":arrow_heading_down: pull"
